export type GenerateMode = "paragraphs" | "sentences" | "words"
export type CapMode = "sentence" | "upper" | "lower" | "title"
export type SentenceLength = "short" | "medium" | "long"
export type DownloadFormat = "txt" | "md" | "html"
export type Preset =
  | "lorem"
  | "developer"
  | "api"
  | "blog"
  | "ecommerce"
  | "social"
  | "product"
  | "errors"
  | "release"